sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

jobs:
  include:
    - language: elm
      stage: test
      before_install:
        - cd frontend/
      install:
        - npm install
        - npm install -g elm-github-install create-elm-app@4.2.16 --unsafe-perm=true
        - elm-app build
      script:
        - elm-app test
    - language: haskell
      stage: test
      before_install:
        - cd core/
        # Download and unpack the stack executable
        - mkdir -p ~/.local/bin
        - export PATH=$HOME/.local/bin:$PATH
        - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      install:
        - travis_wait stack --no-terminal --skip-ghc-check setup
      script:
        - travis_wait stack --no-terminal --skip-ghc-check test
    - language: go
      stage: test
      env:
        - ACCESS_TOKEN="TEST" JWT_SECRET="test"
      script:
        - go test -v -race ./...
    - stage: deploy
      install:
        - wget -qO- https://toolbelt.heroku.com/install.sh | sh
        - heroku container:login
      script:
        - heroku container:push web -a seven-wonders-szetty
        - heroku container:release web -a seven-wonders-szetty