sudo: false

os: osx
jobs:
  include:
    # - language: elm
    #   stage: test
    #   before_install:
    #     - cd frontend/
    #   install:
    #     - npm install
    #     - npm install -g elm-github-install create-elm-app@4.2.16 --unsafe-perm=true
    #     - elm-app build
    #   script:
    #     - elm-app test
    - language: rust
      stage: test
      env:
        - RUSTLER_NIF_VERSION=2.15
      rust:
        - stable
        - beta
        - nightly
      before_install:
        - cd core/
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true
    - language: go
      stage: test
      env:
        - ACCESS_TOKEN="TEST" JWT_SECRET="test"
      script:
        - go test -v -race ./...
    - stage: deploy
      if: branch == master AND (NOT (type IN (push, pull_request)))
      install:
        - wget -qO- https://toolbelt.heroku.com/install.sh | sh
        - heroku container:login
      script:
        - heroku container:push web -a seven-wonders-szetty
        - heroku container:release web -a seven-wonders-szetty