sudo: false

os: osx
osx_image: xcode12.2
jobs:
  include:
    - name: Frontend
      language: elm
      stage: test
      before_install:
        - cd frontend/
      install:
        - npm install
        - npm install -g elm-github-install create-elm-app@4.2.16 --unsafe-perm=true
        - elm-app build
      script:
        - elm-app test
    - name: Core
      language: rust
      stage: test
      env:
        - RUSTLER_NIF_VERSION=2.15
      rust:
        - stable
        - beta
        - nightly
      before_install:
        - cd core/
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true
    - name: Old Backend
      language: go
      stage: test
      env:
        - ACCESS_TOKEN="TEST"
        - JWT_SECRET="test"
      go:
        - "1.16"
    - name: Integration Tests
      language: generic
      stage: test
      env:
        - ACCESS_TOKEN="TEST"
        - JWT_SECRET="test"
        - LOG_LEVEL="error"
      install:
        - cd backend_old
        - go build
        - cd ../integration-tests
        - npm install
      script:
        - ../backend_old/backend_old & npm test
        - kill %1
    - name: Backend
      language: minimal
      stage: test
      before_install:
        - cd backend/
        - brew install elixir
      install:
        - mix local.rebar --force; mix local.hex --force; mix deps.get
      script:
        - mix test
    - stage: deploy
      if: branch == master AND (NOT (type IN (push, pull_request)))
      install:
        - wget -qO- https://toolbelt.heroku.com/install.sh | sh
        - heroku container:login
      script:
        - heroku container:push web -a seven-wonders-szetty
        - heroku container:release web -a seven-wonders-szetty