name:                core
version:             0.0.1
github:              "Szetty/seven_wonders"
license:             MIT
author:              "Arnold & Andra Szederjesi-Dragomir"
copyright:           "2020 Arnold & Andra Szederjesi-Dragomir"

dependencies:
  - base >= 4.7 && < 5
  - ilist
  - containers
  - transformers
  - text
  - random-shuffle
  - warp
  - random

default-extensions:
  - NamedFieldPuns
  - OverloadedStrings
  - DuplicateRecordFields
  - TupleSections

library:
  source-dirs: src

executables:
  core-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - core
    - mu-grpc-server  >=0.3.0
    - mu-protobuf     >=0.3.0
    - mu-rpc          >=0.3.0
    - mu-schema       >=0.3.0

tests:
  core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - core
    - hspec
